# jdbc datasource

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/one_to_one_bidirectional_mapping
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver


    #jpa or hibernate configurations

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      format-sql: true
      dialect: org.hibernate.dialect.MySQLDialect
