# jdbc datasource
server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/school
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver



  #jpa or hibernate configurations

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      format-sql: true
      dialect: org.hibernate.dialect.MySQLDialect


  security:
    user:
      name: user
      password: user

logging:
  level:
    org.springframework.security: DEBUG



