

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8086/realms/org1
          jwk-set-uri: http://localhost:8086/realms/org1/protocol/openid-connect/certs
